//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAdmissionManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public partial class Student
    {
        public int stuId { get; set; }
        public string stuName { get; set; }
        public short stuAge { get; set; }
        public string stuGender { get; set; }
        public System.DateTime stuDOB { get; set; }
        public int stuStatus { get; set; }
        public int stuCourseId { get; set; }
        public Nullable<System.DateTime> stuSuspendTillDate { get; set; }

        public virtual Course Course { get; set; }
        public virtual Student_Status Student_Status { get; set; }
    }
}
